<?php require 'templates/header.phtml' ?>

<h1>Posts</h1>
<?php foreach($posts as $post) : ?>
  <article>
    <a href="post/<?= $post->id ?>">
      <h3><?= $post->title ?></h3>
    </a>
    <p><?= $post->body ?></p>
    <small>
      written by:
      <a href="user/<?= $post->author_id ?>">
        <?= $post->author ?>
      </a>
    </small>
  </article>
  <hr>
<?php endforeach ?>

<?php require 'templates/footer.phtml' ?>
